### ISSUE TITLE
Install on linux

### ISSUE THREAD

**Issue by drdeoc** [k3rn31p4nic/WebCord#2]
rock@rockpi4b:~/Downloads$ go get github.com/k3rn31p4nic/WebCord
go: downloading github.com/k3rn31p4nic/WebCord v0.0.0-20201020121003-2533daaf0497
go get: github.com/k3rn31p4nic/WebCord@v0.0.0-20201020121003-2533daaf0497: parsing go.mod:
        module declares its path as: WebCord
                but was required as: github.com/k3rn31p4nic/WebCord

Arm64 Rockpi Debian 10

Any idea?

**Comment by iamtraction** [comment]
see the updated readme. my username was changed, so needed to update the url.
