### ISSUE TITLE
Unable to install via Windows CMD.

### ISSUE THREAD

**Issue by Ozakinn** [k3rn31p4nic/WebCord#3]
Followed your steps but heres the result:

[
![error](https://user-images.githubusercontent.com/21289418/146504855-33325f38-a072-46f9-ab7f-7564ed2a8ae6.png)
](url)

**Comment by iamtraction** [comment]
if you've got chocolately installed in your system run `refreshenv` and then run `webcord`. otherwise, simply open a new command prompt window and run `webcord`.

**Comment by SyedOmarNoor** [comment]
> if you've got chocolately installed in your system run `refreshenv` and then run `webcord`. otherwise, simply open a new command prompt window and run `webcord`.

i did those but still says not command
(using go install github.com/iamtraction/WebCord@latest cause get not outside module)
